apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.env }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.env }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  - port: {{ .Values.externalPort }}
    targetPort: {{ .Values.port }}
    protocol: TCP
    name: {{ .Chart.Name }}-{{ .Values.env }}
  selector:
    app: {{ .Chart.Name }}-{{ .Values.env }}